console.log(typeof 1)
console.log(typeof "1")
console.log(typeof undefined)
console.log(typeof null)
console.log(typeof {})
console.log(typeof true)
console.log(typeof function(){console.log(123)})

console.log(1 instanceof Number)
console.log("asd" instanceof String)
console.log([] instanceof Array)
console.log({} instanceof Object)
