const module1 = require('./modules/modules1')
const module2 = require('./modules/modules2')
const module3 = require('./modules/modules3')
const uniq = require('uniq')
module1.foo()
module2()
module3.foo()
module3.bar()
const arr = uniq(module3.arr);
console.log(arr)
