const module1 = require('./modules/modules1')
const module2 = require('./modules/modules2')
const module3 = require('./modules/modules3')
module1.foo()
console.log(module)
module2()
module3.foo()
module3.bar()
console.log(module3.arr)
